openapi: 3.0.3
info:
  title: API de gestion des tâches
  version: 1.0.0
  description: >
    Cette API permet de créer, lister, consulter et supprimer des tâches.
    Les tâches sont définies par un modèle Task réutilisable.

servers:
  - url: http://localhost:8000
    description: Serveur local

paths:
  /tasks:
    get:
      summary: Liste toutes les tâches
      responses:
        "200":
          description: Liste des tâches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    post:
      summary: Crée une ou plusieurs tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Liste des nouvelles tâches créées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    delete:
      summary: Supprime plusieurs tâches par liste d'identifiants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                example: 1
      responses:
        "200":
          description: Liste des tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "404":
          description: Tâche(s) non trouvée(s)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found

  /tasks/{id}:
    get:
      summary: Retourne une tâche par son ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tâche
      responses:
        "200":
          description: Tâche trouvée
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found

    delete:
      summary: Supprime une tâche par son ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID de la tâche à supprimer
      responses:
        "200":
          description: Tâche supprimée
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Task not found

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Faire les courses
        completed:
          type: boolean
          example: false
