openapi: 3.0.3
info:
  title: API Produits
  version: 1.0.0
  description: >
    Cette API permet de rechercher et lister des produits avec des filtres (q, limit).

servers:
  - url: http://localhost:8000
    description: Serveur local
